owner_org: "wfp"
author: "WFP - World Food Programme"
license_id: "ODbL"
subnational: 1
caveats: "This dataset was endorsed by the IMWG on August 03/08/2017 as the roads dataset that working group members will use."
methodology: "This dataset is an extract of OSM and updated every hour. It uses OSM tags that match corresponding attributes of the WFP data structure (UNSDI-T) and the values of the tags are used as is."
package_creator: "Amadou"
private: False  # has to be True or False
maintainer: "1c9f2185-4193-4cd2-bcee-87a901faf6a6"
notes: "This dataset is an extraction of roads from OpenStreetMap data made by WFP following UNSDI-T standards.The data is updated in near-real time from OSM servers and include all latest updates."
dataset_source: "OpenStreetMap"
author: "wfp"
state: "active"
